version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017

  node:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app/
    ports:
      - 3339:3339
    volumes:
      - ./:/home/node/app/
    command: ["npm", "start"]
    depends_on:
      - mongo